### ISSUE TITLE
Test to learn which program needs to start first

### ISSUE THREAD

**Issue by zengxiaoqing** [aerorahul/lorenz-da#2]
May I ask if each program is independent. If I need to test, which program should I start with first, and whether additional data is needed?

**Comment by aerorahul** [comment]
@zengxiaoqing 
Each program is independent, however if you want to do variational data assimilation, you will have to generate a static background error covariance matrix.  All necessary data is/can be generated with the scripts in this repository.

`LXX_stats.py` is the first step.  This will create a static background error covariance matrix file, based on the users choice.
Once you have `B`, you can do any of  `truthDA.py`, `varDA.py`, `ensDA.py`, `hybDA.py`.  Be sure to check the configuration in the appropriate `*_param.py`

Good luck.
